src/com/toretto/autoparts/entity/Product.java
package com.toretto.autoparts.entity;

import java.io.Serializable;

public class Product implements Serializable{
	
	private static final long serialVersionUID = 1L;

	private Integer id;

	private String name;
	
	private String description;
	
	private Float price;
	
	private String photoName;
	
	public Product() {
	}
	
	public Product(Integer id, String name, String description, Float price ) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.price = price;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getPrice() {
		return price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	public String getPhotoName() {
		if (photoName == null){
			return String.valueOf("/images/"+this.getId() + ".jpg");
		}
		return photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Product other = (Product) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	

}

src/com/toretto/autoparts/entity/Purchase.java
package com.toretto.autoparts.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class Purchase implements Serializable {

	private Integer id;
	private Date date;
	private Float total;
	private Customer customer;
	private Set<PurchaseItem> itens;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Float getTotal() {
		return total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public void setItens(Set<PurchaseItem> itens) {
		this.itens = itens;
	}

	public Set<PurchaseItem> getItens() {
		if (itens == null) {
			itens = new HashSet<PurchaseItem>();
		}
		return itens;
	}

	public List<PurchaseItem> getOrderedItens() {
		return new ArrayList<PurchaseItem>(getItens());
	}

	public void addItem(Product product, Integer quantity) {
		PurchaseItem itemExistente = getItem(product);
		if (itemExistente != null) {
			updateQuantity(product, itemExistente.getQuantity() + quantity);
		} else {
			getItens().add(new PurchaseItem(product, quantity));
			calculateTotal();
		}
	}

	public void removeItem(PurchaseItem product) {
		getItens().remove(product);
		calculateTotal();
	}

	public PurchaseItem getItem(Product product) {
		PurchaseItem itemAProcurar = new PurchaseItem(product);
		for (PurchaseItem item : getItens()) {
			if (item.getProduct().getId().equals((itemAProcurar.getProduct().getId()))) {
				return item;
			}
		}
		return null;
	}

	public void updateQuantity(Product product, Integer newQuantity) {
		PurchaseItem item = getItem(product);
		if (item == null) {
			throw new IllegalArgumentException("Item not found " + product);
		}
		item.updateQuantity(newQuantity);
		calculateTotal();
	}

	public void calculateTotal() {
		total = 0F;
		for (PurchaseItem item : getItens()) {
			item.calculateTotal();
			total += item.getTotalPrice();
		}
	}

}

WebContent/closedPurchase.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core"> 

<ui:composition template="/template/template.xhtml">
    <ui:define name="body">
      <h3>
        <h:outputFormat value="Purchase Sucessfull" />
      </h3>
        <br /><br />
        <h:outputText value="#{shoppingCartMBean.customer.name}" />
        <h:outputText value=", this is your Purchase number: " />
        <h:outputText value="#{shoppingCartMBean.idGeneratedPurchase}" />
        <br/>
    </ui:define>
  </ui:composition>
</html>

WebContent/index.jsp
<%
    response.sendRedirect(request.getContextPath() + "/login.jsf");
%>

WebContent/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core"> 
      
<head>
	<title>Toretto AutoParts</title>
	
<style type="text/css">
	
#header .subtitle {
  font-size: 1.5em;
  display: block;
  color: #D49768;
}

</style>
	
</head> 
<body> 
	
	<f:facet name="header">
        TORETO AUTO-PARTS
    </f:facet>
    
    <br />
		<br />
		<h:form>
			<table width="58%" border="0" align="center" cellpadding="5" cellspacing="0">
			  <tr>
			  	<td colspan="2" align="center">
			  		<span class="subtitle">WELLCOME TO TORETTO AUTO-PARTS</span><br />
			  	</td>
			  </tr>
	          <tr>
	            <td width="34%"><h:outputLabel for="user" value="User" /></td>
	            <td width="66%"><h:inputText id="user" value="#{loginMBean.customer.email}" size="30" maxlength="20" /></td>
	          </tr>
	          <tr>
	            <td><h:outputLabel for="passWd" value="Password"/></td>
	            <td><h:inputSecret id="passWd" value="#{loginMBean.customer.password}" size="30" maxlength="12" /></td>
	          </tr>
	          <tr>
	            <td colspan="2" align="center">
		            <h:commandButton id="login" action="#{loginMBean.login()}" value="Login"/>
	            </td>
	          </tr>
        	</table>
		</h:form>

</body> 
</html>

WebContent/product.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">
  <ui:composition template="/template/template.xhtml">
    <ui:define name="body">
      <h2>Product List</h2>    
      <h:form>
      
      	<h:link value="Enter to continue" outcome="login" styleClass="link" rendered="#{productMBean.productList.size() == 0}"/>
      	
        <h:dataTable id="productList" value="#{productMBean.productList}" var="item" styleClass="list-content">
           <h:column>
             <table style="width: 100%; margin-top: 10px;">
				<tr>
	            <td class="column" style="width:20%">
	              <h:graphicImage value="#{item.photoName}" height="100px" width="100px">
	                  <f:param name="id" value="#{item.id}" />
	              </h:graphicImage>
	            </td>
	            <td class="column" style="width:55%;text-align: left;">
	              <h:outputText value="#{item.name}" styleClass="product-title" />
	              <span class="product-sumary">
	                <h:outputText value="#{item.description}" escape="false"/>
	              </span>
	            </td>
	            <td class="column" style="width:25%;text-align:center;">
	              <h:outputText value="#{item.price}">
	                <f:convertNumber currencyCode="USD" type="currency" /> 
	              </h:outputText>
	              <br />
	              <h:commandButton  value="Add to cart" action="#{shoppingCartMBean.addToShoppingCart(item)}" style="margin-top: 15px;"/>
	            </td>
	          </tr>
	        </table>             
           </h:column>
        </h:dataTable>

      </h:form>
    </ui:define>
  </ui:composition>
  </html>

WebContent/shoppingCart.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  <html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ui="http://java.sun.com/jsf/facelets">
    
  <ui:composition template="/template/template.xhtml">
    <ui:define name="body">
      <h2>My Cart</h2>    
      <h:form id="formShoppingVCart">
      
        <h:link value="Enter to continue" outcome="login" styleClass="link" rendered="#{productMBean.productList.size() == 0}"/>
      	<h:outputText value="--No itens added--" rendered="#{!shoppingCartMBean.hasItens() and productMBean.productList.size() > 0}"/>
      
        <h:dataTable id="listItens" value="#{shoppingCartMBean.purchaseCart.orderedItens}" var="item" rendered="#{shoppingCartMBean.hasItens()}" styleClass="list-content">
          <h:column style="width: 60%">
          	<f:facet name="header" > <h:outputText value="PRODUCT" /> </f:facet>
            <h:outputText value="#{item.product.name}" />
          </h:column>
          <h:column style="width: 15%">
          	<f:facet name="header" > <h:outputText value="QUANTITY" /> </f:facet>
            <h:outputText value="#{item.quantity}" />
            <f:facet name="footer">  
              <h:outputLabel value="Total"/>  
            </f:facet> 
          </h:column>
          <h:column style="width: 15%; text-align: right;">
          	<f:facet name="header" > <h:outputText value="TOTAL" /> </f:facet>
            <h:outputText value="#{item.totalPrice}">
              <f:convertNumber currencyCode="USD" type="currency" />
            </h:outputText>
            <f:facet name="footer">
              <h:outputText value="#{shoppingCartMBean.purchaseCart.total}">
                <f:convertNumber currencyCode="USD" type="currency" />
              </h:outputText>
            </f:facet>          
          </h:column>
          <h:column>
          	<f:facet name="header" > <h:outputText value="REMOVE" /> </f:facet>
            <h:commandButton value="Remove" action="#{shoppingCartMBean.removeFromCart()}">
              <f:setPropertyActionListener value="#{item}"  target="#{shoppingCartMBean.productToRemove}" />
            </h:commandButton>
          </h:column>  
        </h:dataTable>
        
        <br/><br/>
        <h:link outcome="product" styleClass="link" value="Continue..." rendered="#{productMBean.productList.size() > 0}"/>
        <br/><br/>
         <hr />
          <h:panelGrid columns="2" styleClass="panel-content" rendered="#{productMBean.productList.size() > 0}">
            <h:outputLabel value="Email" for="txtEmail" />
            <h:inputText value="#{shoppingCartMBean.customer.email}" id="txtEmail" size="25" maxlength="40" disabled="true" label="User"/>
          	<h:commandButton action="#{shoppingCartMBean.requestPurchase()}"  value="Finalize"/>
          </h:panelGrid>
        
      </h:form>    
    </ui:define>
  </ui:composition>
  </html>